Repository Brainybrian316/Sweet-Nostalgia, pull requests merged in 2022-06, with the labels that each got.

#75 Feature/completed routes
  controllers/api/candies-routes.js
  controllers/api/candy-routes.js
  controllers/api/candybox-routes.js
  controllers/api/index.js
  controllers/api/old-user-route.js
  controllers/api/product-routes.js
  controllers/api/session-routes.js
  controllers/api/sub-routes.js
  controllers/api/user-routes.js
  controllers/api/users-routes.js
  controllers/dashboard-routes.js
  controllers/home-routes.js
  models/Candies.js
  models/Candy.js
  models/CandyBox.js
  models/Product.js
  models/Subscription.js
  models/Users.js
  models/index.js
  public/js/login.js
  public/js/logout.js
  seeds/candies-seeds.js
  seeds/candy-seeds.js
  seeds/candybox-seeds.js
  seeds/index.js
  seeds/product-seeds.js
  seeds/subscription-seeds.js
  seeds/user-seeds.js
  seeds/users-seeds.js
Labels: bug, enhancement

#78 themes boilerplate
  controllers/home-routes.js
  views/themes.handlebars
Labels: enhancement, good first issue

#80 Develop
  controllers/api/candies-routes.js
  controllers/api/candy-routes.js
  controllers/api/candybox-routes.js
  controllers/api/index.js
  controllers/api/product-routes.js
  controllers/api/session-routes.js
  controllers/api/sub-routes.js
  controllers/api/user-routes.js
  controllers/api/users-routes.js
  controllers/dashboard-routes.js
  controllers/home-routes.js
  controllers/index.js
  controllers/subscription-routes.js
  models/Candies.js
  models/Candy.js
  models/CandyBox.js
  models/Product.js
  models/Subscription.js
  models/Users.js
  models/index.js
  public/css/style.css
  public/js/login.js
  public/js/logout.js
  public/js/signup.js
  public/js/subscription.js
  seeds/candies-seeds 2.js
  seeds/candies-seeds.js
  seeds/candy-seeds.js
  seeds/candybox-seeds 2.js
  seeds/candybox-seeds.js
  seeds/index.js
  seeds/product-seeds.js
  seeds/subscription-seeds 2.js
  seeds/subscription-seeds.js
  seeds/user-seeds.js
  seeds/users-seeds 2.js
  seeds/users-seeds.js
  views/subscription.handlebars
  views/themes.handlebars
Labels: enhancement

#86 readme
  README.md
Labels: documentation

#88 Develop
  public/css/style.css
  public/images/container-background.png
  public/images/header-background.png
  public/images/homepage-candies-image.png
  public/images/homepage-candy-box-image.png
  public/images/homepage-container-graphic-01.png
  public/images/homepage-container-graphic-02.png
  public/images/homepage-container-graphic-03.png
  public/images/modal-background-login.png
  public/images/modal-background-signup.png
  public/images/sweet-nostalgia-logo.png
  public/images/website-body-background.png
  public/images/website-hero-background.png
  public/images/website-theme-container-background.png
  views/homepage.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#91 Develop
  controllers/home-routes.js
  controllers/index.js
  public/css/style.css
  public/js/sign-sub.js
  views/creditcard.handlebars
  views/thankYou.handlebars
Labels: enhancement
