Repository Brainybrian316/Sweet-Nostalgia, pull requests merged in 2022-05, with the labels that each got.

#28 Feature/home routes
  README.md
  config/connection.js
  controllers/home-routes.js
  controllers/index.js
  db/schema.sql
  server.js
  views/homepage.handlebars
  views/layouts/main.handlebars
Labels: good first issue

#58 updated candy model and added user/candy associations in index.js model
  models/index.js
Labels: question

#62 Feature/comments
  controllers/api/candy-routes.js
  controllers/api/index.js
  controllers/api/user-routes.js
  controllers/dashboard-routes.js
  controllers/home-routes.js
  server.js
  utils/auth.js
  views/layouts/main.handlebars
Labels: bug, enhancement

#64 Feature/cleaning code
  controllers/index.js
  models/index.js
Labels: bug

#66 Feature/associations
  controllers/api/candy-routes.js
  controllers/api/user-routes.js
  models/Candy.js
  models/index.js
  seeds/candy-seeds.js
  seeds/user-seeds.js
Labels: bug, enhancement

#71 Feature/appear disappear
  config/connection.js
  controllers/api/user-routes.js
  controllers/dashboard-routes.js
  controllers/home-routes.js
  seeds/user-seeds.js
  utils/auth.js
  views/dashboard.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
Labels: bug, enhancement

#72 Feature/credit card (Initial version)
  public/css/style.css
  public/images/American_Express_logo_(2018).svg
  public/images/Blue_question_mark_icon.svg
  public/images/Diners_Club_Logo3.svg
  public/images/Discover_Card_logo.svg
  public/images/JCB_logo.svg
  public/images/Mastercard_2019_logo.svg
  public/images/UnionPay_logo.svg
  public/images/Visa_2021.svg
  public/js/creditcard-validate.js
  views/creditcard.handlebars
Labels: enhancement
